### ISSUE TITLE
Confirm use of Mesa's data_collection_period

### ISSUE THREAD

**Issue by divilian** [harmonyrose/3rd-Party-Problem#12]
Verify that `election_steps` can be passed as `data_collection_period` to the `batch_run()` function, obviating need to use it in `Society::step()`.

**Comment by divilian** [comment]
@harmonyrose: did we consider this and conclude that we do actually have to do the "`if self.step_num % 50:`" thing in `Society::step()`, rather than have the Mesa data_collector trigger it? I have a vague recollection...

**Comment by harmonyrose** [comment]
@divilian We didn't come to any conclusions about this. The data_collector was initially set up to trigger elections every 50 steps, but it was triggering an election at every step. I did `if self.step_num % 50` as an easy fix. It very well may be possible that the data_collector can do this and there was just a bug in the code.

**Comment by divilian** [comment]
I'm closing this, since it doesn't seem worth worrying about (everything's working).
