### ISSUE TITLE
Tag Zotero related work

### ISSUE THREAD

**Issue by divilian** [harmonyrose/3rd-Party-Problem#22]
Let's label with Zotero "tags" which of these each paper falls under:

- parties-two
- parties-multiple
- topology-grid
- topology-graph
- topology-complete
- opinions-discrete
- opinions-continuous
- opinions-scalar
- opinions-vector
- interaction-pushPull
- interaction-pullOnly
- receptivity- ...an abbreviation for the receptivity theory/algorithm...
- voting- ...an abbreviation for the voting algorithm...
- turnout- ...an abbreviation for how turnout is determined...
- campaign- ...an abbreviation for what levers a campaign has...
- massMedia  ...maybe this is just a 'present or absent' tag? based on whether that's a factor in the model at all

So, Kottonau (one of my papers) would be labeled with these tags: parties-two, topology-graph, opinions-continuous, opinions-scalar, interaction-pullOnly, receptivity-RAS, receptivity-impressionFormation, voting-calculated, turnout-attitudeStrength, campaign-partyMessaging, massMedia

And for completeness, Davies&Peura (when it exists) would have: parties-multiple, topology-graph, opinions-continuous, opinions-vector, interaction-pushPull, campaign-issueAdjustment

**Comment by divilian** [comment]
Mine are done.

**Comment by harmonyrose** [comment]
Mine are all labeled now.
