### ISSUE TITLE
Track # of voteless candidates

### ISSUE THREAD

**Issue by divilian** [harmonyrose/3rd-Party-Problem#28]
i.e., how often does line 240etc get run?

**Comment by divilian** [comment]
Actually, reopen and ask @harmonyrose about this. On line 247-ish, if "`max(vote_counts.values()) == 0)`" is true, does this mean (a) the candidate actually got zero votes in the election, or (b) the candidate discovered that if it chose to shift to a certain chase point, it would then get zero votes in the election?

**Comment by harmonyrose** [comment]
If `max(vote_counts.values()) == 0)` is true, then the candidate discovered that for _every_ chase point it tried, it got zero votes in the hypothetical election. If this is the case, the candidate just moves to the first point listed in the `vote_counts` dictionary, given the point is between 0 and 1 for each issue.

**Comment by divilian** [comment]
Ah, okay. Makes sense. I think my code for this is correct, then. (d3e0443)
